const tseslint = require('typescript-eslint');

module.exports = tseslint.config(
    {
        ignores: ['dist/**', 'build/**', 'node_modules/**'],
    },
    ...tseslint.configs.recommended,
    {
        files: ['src/**/*.ts'],
        languageOptions: {
            parserOptions: {
                projectService: true,
                tsconfigRootDir: __dirname,
            },
            globals: {
                document: 'readonly',
                window: 'readonly',
                location: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                requestAnimationFrame: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                MutationObserver: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                Blob: 'readonly',
                FileReader: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                HTMLElement: 'readonly',
                HTMLButtonElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                HTMLSelectElement: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLStyleElement: 'readonly',
                HTMLAnchorElement: 'readonly',
                Element: 'readonly',
                MouseEvent: 'readonly',
                PointerEvent: 'readonly',
                KeyboardEvent: 'readonly',
                InputEvent: 'readonly',
                DOMRect: 'readonly',
                Response: 'readonly',
                fetch: 'readonly',
                localStorage: 'readonly',
                GM_addStyle: 'readonly',
                GM_setValue: 'readonly',
                GM_getValue: 'readonly',
            },
        },
        rules: {
            'no-console': 'off',
        },
    },
);
